# Generated by Django 5.2.4 on 2025-07-22 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_clubs', '0001_initial'),
        ('books', '0002_alter_bookauthor_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookClubReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start_date', models.DateTimeField()),
                ('start_date', models.DateTimeField(null=True)),
                ('planned_finish_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('WAITING_FOR_START', 'WAITING_FOR_START'), ('STARTED', 'STARTED'), ('DONE', 'DONE'), ('CANCELLED', 'CANCELLED')], default='WAITING_FOR_START', max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('book_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_clubs.bookclub')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
