# Generated by Django 5.2.4 on 2025-07-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='last_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
