# Generated by Django 5.2.4 on 2025-07-22 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookClubReadingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start_date', models.DateTimeField()),
                ('start_date', models.DateTimeField(null=True)),
                ('planned_finish_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField(null=True)),
                ('description', models.CharField(max_length=512)),
                ('target_percent', models.PositiveSmallIntegerField(default=0)),
                ('book_club_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.bookclubreading')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
