version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: "make start"
    env_file:
      - .env
    expose:
      - "8000"

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./static:/static:ro
      - ./dist:/dist:ro
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django
