# Generated by Django 5.2.4 on 2025-07-22 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('IDLE', 'IDLE'), ('VOTING', 'VOTING'), ('WAIT_FOR_READING', 'WAIT_FOR_READING'), ('READING', 'READING')], default='IDLE', max_length=255)),
                ('members', models.ManyToManyField(related_name='member_clubs', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_clubs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
